name: Setup conan, meson, ninja and gcovr

runs:
  using: "composite"
  steps:
    - name: Install conan, meson, ninja and gcovr
      run: pip install conan meson ninja gcovr
      shell: bash

    - name: Create default profile
      run: conan profile detect
      shell: bash
